/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'Thanks, lets play!': '感谢，让我们开始吧！',
    'Set': '设置',
    'Start to gain points, but you can\'t pick numbers & upgrades!': '开始获得点数，但您无法选择数字和升级！',
    'Story of Creating the Gam': '创建游戏的故事',
    'super balanced points': '超级平衡点',
    'Thanks for Ideas: Marc & Unpingabot!': '感谢您的想法：Marc 和 Unpingabot！',
    'Upgrades': '升级',
    'Welcome to \"the Balanced Upgrade!\"': '欢迎来到“平衡升级！”',
    'You are started to pick any numbers and upgrades, then start to gain points!': '您开始选择任何数字和升级，然后开始获得点数！',
    'Picked Number': '选择数字',
    'Hello!': '哈喽!',
    'Loading Game...': '加载游戏...',
    'Multiply points gain by 1.0x': '点数增益乘以 1.0x',
    'Have {{ format(UPGRADES.superBalanced.getUnspent(), 0) }} unspent super balanced points': '有 {{ format(UPGRADES.superBalanced.getUnspent(), 0) }} 未使用的超级平衡点',
    'Need start to make balanced points first!': '首先需要平衡点数！',
    'Presented balanced upgrades': '提出了平衡的升级',
    'Presented Style & Tabs, more upgrades': '呈现的样式和标签，更多的升级',
    'Presented SUPER balanced points & types': '呈现超级平衡的点和类型',
    'Presented upgrades & balanced points': '呈现升级和平衡点',
    'Story of Creating the Game': '创建此游戏的故事',
    'You have': '你有',
    'Cost: {{ format(UPGRADES.balanced[x].cost(), 0) }} BP': '成本: {{ format(UPGRADES.balanced[x].cost(), 0) }} 平衡点',
    'Final features, ending & credits! The game is READY!': '最终功能，结尾和字幕!游戏准备好了!',
    'Hard Reset': '硬复位',
    'Have': '有',
    'Auto-Balance': '自动平衡',
    'balanced points': '平衡点',
    'Achievements, fixed bugs, and more...': '成就，修复bug，和更多…',
    'Got Infinity!': '得到无限！',
    'Credits': '鸣谢',
    'I am SUPER balancer': '我是超级平衡者',
    'Reach over 1.798e308 points to complete game!': '达到超过 1.798e308 点即可完成游戏！',
    'Illuminati Confirmed!': '光明会确认！',
    'Really bug?!': '真的bug？！',
    'Super Double': '超级双倍',
    'TEN TAN TIN': '十士式',
    'Too fast?': '太快了？',
    'First Balanced!': '第一个平衡!',
    'Get 10 super balanced points. Reward: Balanced points resets nothing, if you can finish to get balanced points.': '获得10个超级平衡点。 奖励：平衡点数不重置，完成即可获得平衡点数。',
    'Get 4 super balanced points. Reward: Unlock Auto-Balance.': '获得4个超级平衡点。 奖励：解锁自动平衡。',
    'Get 5 balanced points.': '获得 5 平衡点。',
    'Get first balanced point.': '获得第一个平衡点。',
    'Get super balanced point.': '获得超级平衡点。',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    'Loading...': '加载中...',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Day ": "天数 ",
    "Multiply points gain based on your points.": "乘以点数增益基于你的点数。",
    "Multiply points gain by ": "乘以点数增益 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^(.+)\/s\) points$/, '$1\秒\) 点数'],
    [/^Get (.+) super balanced points.$/, '获得 $1 个超级平衡点。'],
    [/^(.+) Numbers used.$/, '$1 数字已使用'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);