/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'Thanks, lets play!': '感谢，让我们开始吧！',
    'Set': '设置',
    'Start to gain points, but you can\'t pick numbers & upgrades!': '开始获得点数，但您无法选择数字和升级！',
    'Story of Creating the Gam': '创建游戏的故事',
    'super balanced points': '超级平衡点',
    'Thanks for Ideas: Marc & Unpingabot!': '感谢您的想法：Marc 和 Unpingabot！',
    'Upgrades': '升级',
    'Welcome to \"the Balanced Upgrade!\"': '欢迎来到“平衡升级！”',
    'You are started to pick any numbers and upgrades, then start to gain points!': '您开始选择任何数字和升级，然后开始获得点数！',
    'Picked Number': '选择数字',
    'Hello!': '哈喽!',
    'Loading Game...': '加载游戏...',
    'Multiply points gain by 1.0x': '点数增益乘以 1.0x',
    'Have {{ format(UPGRADES.superBalanced.getUnspent(), 0) }} unspent super balanced points': '有 {{ format(UPGRADES.superBalanced.getUnspent(), 0) }} 未使用的超级平衡点',
    'Need start to make balanced points first!': '首先需要平衡点数！',
    'Presented balanced upgrades': '提出了平衡的升级',
    'Presented Style & Tabs, more upgrades': '呈现的样式和标签，更多的升级',
    'Presented SUPER balanced points & types': '呈现超级平衡的点和类型',
    'Presented upgrades & balanced points': '呈现升级和平衡点',
    'Story of Creating the Game': '创建此游戏的故事',
    'You have': '你有',
    'Cost: {{ format(UPGRADES.balanced[x].cost(), 0) }} BP': '成本: {{ format(UPGRADES.balanced[x].cost(), 0) }} 平衡点',
    'Final features, ending & credits! The game is READY!': '最终功能，结尾和字幕!游戏准备好了!',
    'Hard Reset': '硬复位',
    'Have': '有',
    'Auto-Balance': '自动平衡',
    'balanced points': '平衡点',
    'Achievements, fixed bugs, and more...': '成就，修复bug，和更多…',
    'Got Infinity!': '得到无限！',
    'Credits': '鸣谢',
    'I am SUPER balancer': '我是超级平衡者',
    'Reach over 1.798e308 points to complete game!': '达到超过 1.798e308 点即可完成游戏！',
    'Illuminati Confirmed!': '光明会确认！',
    'Really bug?!': '真的bug？！',
    'Super Double': '超级双倍',
    'TEN TAN TIN': '十士式',
    'Too fast?': '太快了？',
    'First Balanced!': '第一个平衡!',
    'Get 10 super balanced points. Reward: Balanced points resets nothing, if you can finish to get balanced points.': '获得10个超级平衡点。 奖励：平衡点数不重置，完成即可获得平衡点数。',
    'Get 4 super balanced points. Reward: Unlock Auto-Balance.': '获得4个超级平衡点。 奖励：解锁自动平衡。',
    'Get 5 balanced points.': '获得 5 平衡点。',
    'Get first balanced point.': '获得第一个平衡点。',
    'Get super balanced point.': '获得超级平衡点。',
    'Balanced': '平衡',
    'Cancel to gain points': '取消获得点数',
    'Cancel to make balanced points': '取消以取得平衡点',
    'Game made by MrRedShark77 in Mini-GameJam': 'Game made by MrRedShark77 in Mini-GameJam',
    'Super Balanced': '超级平衡',
    'Boost': '提升',
    'Adds a new effect for numbers': '为数字添加新效果',
    'Less Requirement': '更少的要求',
    'Makes all numbers better': '使所有数字更好',
    'Makes Number Upgrade #2 be stronger': '使数字升级 #2 更强大',
    'More numbers': '更多数字',
    'More options': '更多选项',
    'Strong Upgrade': '强力升级',
    'Weak Requirement': '更弱的需求',
    'You can pick another number': '你可以选择另一个数字',
    '你有 {{ format(UPGRADES.balanced.getUnspentBP(), 0) }} unspent balanced 点数': '你有 {{ format(UPGRADES.balanced.getUnspentBP(), 0) }} 未花费的平衡点数',
    '• 1 - Adds a new effect for numbers': '• 1 - 为数字添加新效果',
    '• 1 - Maximum numbers is increased by 5': '• 1 - 最大数字增加 5',
    '• 2 - Numbers are 15% stronger': '• 2 - 数字强 15%',
    '• 2 - Unlocks new balanced upgrade': '• 2 - 解锁新的平衡升级',
    '• 3 - Adds +1 number slot': '• 3 - 添加 +1 数字槽',
    '• 3 - Makes upgrade 3 43.519% stronger (based on your super balanced points': '• 3 - 使升级 3 强度提高 43.519%（基于你的超级平衡点',
    '• 4 - Maximum numbers is increased by 5': '• 4 - 最大数字增加 5',
    '• 4 - Upgrade 2 effect is squared': '• 4 - 升级 2 效果平方',
    '• 5 - Upgrade 4 are 15% stronger': '• 5 - 升级 4 强度提高 15%',
    '• 6 - Adds +1 number slot & +1 max numbers': '• 6 - 添加 +1 数字槽和 +1 最大数字',
    '• 6 - Unlocks new balanced upgrade': '• 6 - 解锁新的平衡升级',
    '• 7 - Balanced upgrade \"Less Requirement\" are squared': '• 7 - 平衡升级“更少的需求”被平方',
    '• 7 - Maximum numbers is increased by 5': '• 7 - 最大数字增加 5',
    '• 8 - Makes numbers are 5.474% stronger (based on your super balanced points': '• 8 - 使数字增强 5.474%（基于您的超级平衡点',
    '• 9 - Adds +1 max numbers': '• 9 - 添加 +1 最大数字',
    '• 9 - Balanced upgrade \"Weak Requirement\" are 10% stronger': '• 9 - 平衡升级“更弱的需求”增强 10%',
    'Good luck :': '祝你好运 :',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    'Loading...': '加载中...',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Day ": "天数 ",
    "Multiply points gain based on your points.": "乘以点数增益基于你的点数。",
    "Multiply points gain by ": "乘以点数增益 ",
    "Boosts points based on balanced points.": "提升点数基于平衡点。",
    "Divides balanced points requirement based on your super balanced points (": "根据您的超级平衡点划分平衡点要求（",
    "Root balanced points requirement based on your balanced points (": "根平衡点要求基于您的平衡点（",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^(.+) 点数去获得平衡点$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^(.+) points to get balanced point$/, '$1 点数去获得平衡点'],
    [/^Get (.+) super balanced points.$/, '获得 $1 超级平衡点。'],
    [/^(.+)\/s\) points$/, '$1\秒\) 点数'],
    [/^• 8 \- Makes upgrades (.+)\% stronger \(based on your balanced points$/, '• 8 \- 使升级强度提高 $1\%（基于您的平衡点数'],
    [/^• 5 \- Makes numbers are (.+)\% stronger \(based on your balanced points$/, '• 5 \- 使数字增强 $1\%（基于您的平衡点'],
    [/^(.+) Numbers used.$/, '$1 数字已使用'],
    [/^(.+) balanced points to get super balanced point$/, '$1 平衡点去获得超平衡点'],
    [/^Picked upgrade in next number slot effect is raised by (.+) \(cannot affect by this other$/, '下一个编号槽中选择的升级效果提高 $1（不受此其他影响'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);